name: Build site + nightly cards.ndjson(.gz)

on:
  schedule:
    - cron: '0 10 * * *'   # 10:00 UTC
    - cron: '0 9 * * *'    # 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/Denver
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install converter deps
        run: |
          if [ -f apps/mtg-browser/requirements.txt ]; then pip install -r apps/mtg-browser/requirements.txt; fi

      - name: Generate NDJSON (gz + plain)
        run: |
          python apps/mtg-browser/fetch_scryfall_to_ndjson.py --output cards.ndjson.gz
          python apps/mtg-browser/fetch_scryfall_to_ndjson.py --output cards.ndjson --plain

      - name: Prepare Pages artifact (site + /db files)
        run: |
          set -e
          mkdir -p public/db
          # copy the site into public/ (rsync is available on ubuntu-latest)
          rsync -a --delete --exclude '.git' --exclude '.github' ./ public/
          # drop the NDJSON files into /db
          mv cards.ndjson.gz public/db/
          mv cards.ndjson    public/db/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
