name: Build site + nightly cards.ndjson(.gz)

on:
  schedule:
    - cron: '0 10 * * *'   # 10:00 UTC
    - cron: '0 9 * * *'    # 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install converter deps
        run: |
          if [ -f apps/mtg-browser/requirements.txt ]; then
            pip install -r apps/mtg-browser/requirements.txt
          fi

      - name: Generate NDJSON (.gz only)
        run: |
          set -euxo pipefail
          python apps/mtg-browser/fetch_scryfall_to_ndjson.py --output /tmp/cards.ndjson.gz
          ls -lh /tmp/cards.ndjson.gz

      - name: Prepare Pages artifact
        run: |
          set -euxo pipefail
          rm -rf public
          mkdir -p public/db
          rsync -a --delete --exclude '.git' --exclude '.github' --exclude 'public' ./ public/
          mv /tmp/cards.ndjson.gz public/db/
          du -h public/db/cards.ndjson.gz
          test -s public/db/cards.ndjson.gz

      - uses: actions/upload-pages-artifact@v3
        with: { path: public }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: { name: github-pages }
    permissions: { pages: write, id-token: write }
    steps:
      - uses: actions/deploy-pages@v4
