name: Build site + nightly cards.ndjson.gz

on:
  schedule:
    - cron: '0 10 * * 1'   # after Scryfall updates
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Show tree (debug)
        run: |
          echo "Repo root:"
          ls -la
          echo "apps/mtg-browser:"
          ls -la apps/mtg-browser || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install converter deps
        run: |
          if [ -f apps/mtg-browser/requirements.txt ]; then
            pip install -r apps/mtg-browser/requirements.txt
          fi
          python -V

      - name: Generate NDJSON (.gz only)
        shell: bash
        run: |
          set -euxo pipefail
          python apps/mtg-browser/fetch_scryfall_to_ndjson.py --output /tmp/cards.ndjson.gz
          ls -lh /tmp/cards.ndjson.gz
          test -s /tmp/cards.ndjson.gz

      - name: Prepare Pages artifact (preserve root index; publish app + /db)
        shell: bash
        run: |
          set -euxo pipefail
          rm -rf public
          mkdir -p public/db

          # Copy the repository contents into public/ WITHOUT overwriting root index.
          # (We just mirror your repo structure; no special-case copying.)
          rsync -a \
            --exclude='.git/' --exclude='.github/' --exclude='public/' \
            ./ public/

          # Ensure Jekyll doesn't process anything
          touch public/.nojekyll

          # Place generated data at /db/cards.ndjson.gz (repo root path)
          mv /tmp/cards.ndjson.gz public/db/

          echo "Public tree (top-level):"
          ls -la public
          echo "Public tree (/db):"
          ls -la public/db
          du -h public/db/cards.ndjson.gz

          # Optional sanity checks (don't fail if root index isn't present)
          test -s public/db/cards.ndjson.gz
          [ -f public/index.html ] || true
          [ -f public/apps/mtg-browser/index.html ] || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
