name: Rebuild website (no cards job)

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  site:
    runs-on: ubuntu-latest
    env:
      # If you use a custom domain, set this to https://yourdomain.tld
      PAGES_ORIGIN: https://${{ github.repository_owner }}.github.io
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Show tree (debug)
        run: |
          echo "Repo root:"; ls -la
          echo "apps/mtg-browser:"; ls -la apps/mtg-browser || true

      - name: Prepare Pages artifact
        shell: bash
        run: |
          set -euxo pipefail
          rm -rf public
          mkdir -p public/db

          rsync -a \
            --exclude='.git/' --exclude='.github/' --exclude='public/' \
            ./ public/

          touch public/.nojekyll

          # Keep the latest cards file without regenerating it
          URL="${PAGES_ORIGIN}/${REPO_NAME}/db/cards.ndjson.gz"
          echo "Trying to pull existing cards file from: $URL"
          curl -fsSL "$URL" -o public/db/cards.ndjson.gz || echo "No existing cards.ndjson.gz found; continuing."

          ls -la public || true
          ls -la public/db || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
